apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reddit.fullname" . }}-frontend
  labels:
    component: frontend
    {{- include "reddit.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: frontend
      {{- include "reddit.selectorLabels" . | nindent 6 }}
  strategy: {{- toYaml .Values.deploymentStrategy | nindent 4 }}
  template:
    metadata:
      labels:
        component: frontend
        {{- include "reddit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{.Values.frontend.version}}"
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reddit.fullname" . }}-frontend
  labels:
    component: frontend
    {{- include "reddit.labels" . | nindent 4}}
spec:
  type: ClusterIP 
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: frontend
    {{- include "reddit.selectorLabels" . | nindent 4 }}
