apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.graphql.fullnameOverride }}
  labels:
    component: graphql
    {{- include "reddit.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      component: graphql
      {{- include "reddit.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        component: graphql
        {{- include "reddit.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: graphql
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command: [ "uvicorn", "service.ariadne_client:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.graphql.fullnameOverride }}
  labels:
    component: graphql
    {{- include "reddit.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: graphql
  selector:
    component: graphql
    {{- include "reddit.selectorLabels" . | nindent 4 }}