apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "reddit.fullname" . }}-ingress
spec:
  rules:
  - host: localhost
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pdm-reddit-frontend
            port:
              number: 80
      - path: /graphql
        pathType: Prefix
        backend:
          service:
            name: graphql
            port:
              number: 8000